### PR TITLE
Fix issue where exe files were not removed during uninstall.

### LINKED ISSUE #1641: GetAllSquirrelAwareApps locks all exe files, therefore the uninstall process can't delete these exe files
**Squirrel version(s)**
1.9.2

**Description**
uninstall process locks the exe files in the app dir, so it can't remove them, which ends up in a folder which isn't empty

**Steps to recreate**
uninstall a squirrel installation which contains multiple exe files

**Expected behavior**
exe files should be removed from the app folder

**Actual behavior**
exe files aren't being removed from the app folder

**Additional information**
I've isolated the issue to this line, in GetAllSquirrelAwareApps method:
            return di.EnumerateFiles()
                .Where(x => x.Name.EndsWith(".exe", StringComparison.OrdinalIgnoreCase))
                .Select(x => x.FullName)
                .Where(x => (GetPESquirrelAwareVersion(x) ?? -1) >= minimumVersion)
                .ToList();
Something in this line must be locking the files

### PR DESCRIPTION
**Pull request by johan-lindqvist**
This error occurred due to a disposable resource not being disposed.

Tested with our application and the change resolves the issue of exe-files not being removed since version 2.0.0.

Fixes #1641 

Sidenote: there's still two files left after an uninstall, a ".dead"-file, and Update.exe as described in #1586, but if I understand correctly that is expected behavior?

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Looks good to me!

**Comment by jltjohanlindqvist** [comment]
@anaisbetts any chance of getting this reviewed? We currently use a forked version of this but it would be nice to have it in the main package.

**Comment by anaisbetts** [comment]
Please don't reformat the code according to some other formatting style

File: src/Squirrel/SquirrelAwareExecutableDetector.cs [hunk 1]
```diff
@@ -29,32 +29,34 @@ public static List<string> GetAllSquirrelAwareApps(string directory, int minimum
...
                 GetAssemblySquirrelAwareVersion(fullname) ?? GetVersionBlockSquirrelAwareValue(fullname));
         }
 
         static int? GetAssemblySquirrelAwareVersion(string executable)
         {
             try {
-                var assembly = AssemblyDefinition.ReadAssembly(executable);
-                if (!assembly.HasCustomAttributes) return null;
+                using (var assembly = AssemblyDefinition.ReadAssembly(executable))
+                {
```
Comment (anaisbetts) [inline src/Squirrel/SquirrelAwareExecutableDetector.cs:40]: :arrow_up:, the bracket belongs on the same line

Comment (jltjohanlindqvist) [reply src/Squirrel/SquirrelAwareExecutableDetector.cs]: Updated to what I think you meant.
